| 2024-10-24 23:52:29,254 | WARNING | Неверный тип данных для объекта Runner | test_run
Traceback (most recent call last):
  File "D:\PythonProjectAll\module_12\tests_12_4.py", line 23, in test_run
    run2 = rt_with_exceptions.Runner(22)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjectAll\module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
| 2024-10-24 23:52:29,255 | WARNING | Неверная скорость для Runner | test_walk
Traceback (most recent call last):
  File "D:\PythonProjectAll\module_12\tests_12_4.py", line 12, in test_walk
    run1 = rt_with_exceptions.Runner('Max', -1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonProjectAll\module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
